### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by medikoo** [acdaniel/webmake-less#1]
Hello @acdaniel are you interested in maintaining this module?

If it's so, it deserves the update as described in https://github.com/medikoo/modules-webmake/issues/22#issuecomment-19804508

If you don't have time for that, I'll be happy to take care of it. Let me know.

**Comment by acdaniel** [comment]
The develop branch has been updated to use the new css type. I tested and it seems to work well. Take a look and let me know what you think.

**Comment by medikoo** [comment]
It looks great, just `exports.noDependencies` is not needed anymore.. as it's obvious that css is not fed with other requires.

**Comment by acdaniel** [comment]
Great. I've made the update and will release shortly.
